### ISSUE TITLE
What is needed?

### ISSUE THREAD

**Issue by thetooth** [embeddedgo/kendryte#1]
I have a handful of k210 modules and boards on the way so I am wondering what blockers are holding up things like SPI or PWM. Am happy to get stuck into some HAL layer stuff but am unfamiliar with SVD so not sure how much I can help.

Thanks for your work, it is very cool to be able to run go like this.

**Comment by embeddedgo** [comment]
The main "blocker" is a lack of contributors and a lack of free time. I have to keep the Embedded Go compiler in sync with the original one (it's fast moving point). There are also noos runtime and embedded packages that needs some improvements from time to time (eg. recently added support for PLIC nested interrupts). There are also other supported platforms (nrf5 and stm32).

The k210 platform is very important for Embedded Go because of its **two** RISC-V cores and unusual capabilities. It helped a lot to revise the noos port design choices.

I'm currently working on [hal/uarths](https://github.com/embeddedgo/kendryte/blob/master/hal/uarths) driver (Tx is completed but Rx need some work). The next one will be [hal/uart](https://github.com/embeddedgo/kendryte/blob/master/hal/uart) (for now only no-DMA version). After that I plan to start working on hal/spi and try to write DMA based driver for it. Eventually I want to send some work to the K210 KPU over onboard Maix Bit USB to UART converter and display the result on a SPI LCD (eg. FT8xx based one). I **slowly** walk this path...
 
If you've some free time to contribute to this project please select one peripheral and try to add support for it to the HAL.

You've mentioned SPI and PWM. You can start play with PWM using [p/timer](https://github.com/embeddedgo/kendryte/blob/master/p/timer) I've just generated from SVD.

The K210 timers seem to be derived from DW_apb_timer (Synopsys DesignWare APB Timer). Google it for the documentation. You can find the documentation for the most of K210 APB peripherals in the Cyclone V Hard Processor System
Technical Reference Manual (google for cv_54001.pdf file). See also original [Kendryte drivers](https://github.com/kendryte/kendryte-standalone-sdk/tree/develop/lib/driverscode) and [Kendryte demos](https://github.com/kendryte/kendryte-standalone-demo) for inspiration.

To start with PWM you probably need to connect a timer channel to some pin. See fpioa.TIMERn_TOGGLEm in [hal/fpioa funtion list](https://github.com/embeddedgo/kendryte/blob/master/hal/fpioa/pin.go#L83).

The usual way to add support for a new peripheral to the HAL is to generate p/someperiph from SVD and play with it this way using raw registers. After understand it more you can try write more idiomatic interface in hal/someperiph/periph.go and after testing it write driver in hal/someperiph/driver.go. I don't know this procedure suits K210 timers.

Fill free to ask questions if you have any trouble.

**Comment by thetooth** [comment]
Thanks, I have received hardware and ported some application code over, very seamless so I would say you've done a great job so far. A burn in test lasted >24hrs with some very unoptimized code making use heavy of the HAL, go routines and garbage collector without issue.

I took a quick pass at SPI already to see how in over my head I was, here is the peripheral struct created according to SVD:
```
// Copyright 2020 The Embedded Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package spi

import (
	"embedded/mmio"
	"unsafe"

	"github.com/embeddedgo/kendryte/hal/internal"
	"github.com/embeddedgo/kendryte/p/bus"
	"github.com/embeddedgo/kendryte/p/mmap"
	"github.com/embeddedgo/kendryte/p/sysctl"
)

// Periph represents SPI peripheral.
type Periph struct {
	ctrlr0           mmio.U32     // Control Register 0
	ctrlr1           mmio.U32     // Control Register 1
	ssienr           mmio.U32     // Enable Register
	mwcr             mmio.U32     // Microwire Control Register
	ser              mmio.U32     // Slave Enable Register
	baudr            mmio.U32     // Baud Rate Select
	txftlr           mmio.U32     // Transmit FIFO Threshold Level
	rxftlr           mmio.U32     // Receive FIFO Threshold Level
	txflr            mmio.U32     // Transmit FIFO Level Register
	rxflr            mmio.U32     // Receive FIFO Level Register
	sr               mmio.U32     // Status Register
	imr              mmio.U32     // Interrupt Mask Register
	isr              mmio.U32     // Interrupt Status Register
	risr             mmio.U32     // Raw Interrupt Status Register
	txoicr           mmio.U32     // Transmit FIFO Overflow Interrupt Clear Register
	rxoicr           mmio.U32     // Receive FIFO Overflow Interrupt Clear Register
	rxuicr           mmio.U32     // Receive FIFO Underflow Interrupt Clear Register
	msticr           mmio.U32     // Multi-Master Interrupt Clear Register
	icr              mmio.U32     // Interrupt Clear Register
	dmacr            mmio.U32     // DMA Control Register
	dmatdlr          mmio.U32     // DMA Transmit Data Level
	dmardlr          mmio.U32     // DMA Receive Data Level
	idr              mmio.U32     // Identification Register
	ssic_version_id  mmio.U32     // DWC_ssi component version
	dr               [36]mmio.U32 // Data Register
	rx_sample_delay  mmio.U32     // RX Sample Delay Register
	spi_ctrlr0       mmio.U32     // SPI Control Register
	_                mmio.U32     // Reserved
	xip_mode_bits    mmio.U32     // XIP Mode bits
	xip_incr_inst    mmio.U32     // XIP INCR transfer opcode
	xip_wrap_inst    mmio.U32     // XIP WRAP transfer opcode
	xip_ctrl         mmio.U32     // XIP Control Register
	xip_ser          mmio.U32     // XIP Slave Enable Register
	xrxoicr          mmio.U32     // XIP Receive FIFO Overflow Interrupt Clear Register
	xip_cnt_time_out mmio.U32     // XIP time out register for continuous transfers
	endian           mmio.U32     // ENDIAN
}

type WorkMode uint8

const (
	MODE0 WorkMode = iota
	MODE1
	MODE2
	MODE3
)

type FrameFormat uint8

const (
	STANDARD FrameFormat = iota
	DUAL
	QUAD
	OCTAL
)

func SPI(n int) *Periph {
	if n < 0 || n > 3 {
		panic("spi: bad number")
	}
	var p *Periph
	switch n {
	case 0:
		p = (*Periph)(unsafe.Pointer(mmap.SPI0_BASE))
	case 1:
		p = (*Periph)(unsafe.Pointer(mmap.SPI1_BASE))
	case 2:
		p = (*Periph)(unsafe.Pointer(mmap.SPI2_BASE))
	case 3:
		p = (*Periph)(unsafe.Pointer(mmap.SPI3_BASE))
	}
	return p
}

func (p *Periph) Bus() bus.Bus {
	return bus.APB0
}

func (p *Periph) n() int {
	switch uintptr(unsafe.Pointer(p)) {
	case mmap.SPI0_BASE:
		return 0
	case mmap.SPI1_BASE:
		return 1
	case mmap.SPI2_BASE:
		return 2
	case mmap.SPI3_BASE:
		return 3
	}
	return -1
}

func (p *Periph) EnableClock() {
	if p.n() == 2 {
		panic("spi: trying to enable clock on slave peripheral")
	}
}
```

And here is a quick pass at a driver interface:
```
package spi

type Device struct {
	p *Periph

	workMode      uint8
	frameFormat   uint8
	dataBitLength uint8
	endian        uint8
}

func (d *Device) Init(options ...func(*Device)) {
	for _, opt := range options {
		opt(d)
	}

	var dfsOffset, frfOffset, workModeOffset uint8
	switch d.p.n() {
	case 0:
		fallthrough
	case 1:
		dfsOffset = 16
		frfOffset = 21
		workModeOffset = 6
	case 2:
		panic("spi: cannot init spi2 slave device as master")
	case 3:
		fallthrough
	default:
		dfsOffset = 0
		frfOffset = 22
		workModeOffset = 8
	}
	if d.p.baudr == 0 {
		d.p.baudr = 0x14
	}
	d.p.imr = 0x00
	d.p.dmacr = 0x00
	d.p.dmatdlr = 0x10
	d.p.dmardlr = 0x00
	d.p.ser = 0x00
	d.p.ssienr = 0x00
	d.p.ctrlr0 = (d.workMode << workModeOffset) | (d.frameFormat << frfOffset) | ((d.dataBitLength - 1) << dfsOffset)
	d.p.spi_ctrlr0 = 0
	d.p.endian = d.endian
}

func Simple() func(*Device) {
	return func(d *Device) {
		d.workMode = uint8(MODE0)
		d.frameFormat = uint8(STANDARD)
		d.dataBitLength = 8
		d.endian = 0
	}
}
```
This is a direct port of the kendryte SDK obviously, my approach here is to allow options to be supplied as functions so that there can be both an easy mode for beginners or people that just want it to work as well as individual parameters for more unusual setups. I am also concerned about the struct visibility, currently only the HAL can access registers directly which would make it quite annoying if someone wanted to poke around, though perhaps it's better left hidden?

Anyway, I will start on the PWM now and leave SPI for later as I think getting timers working would be useful and much more achievable.

**Comment by embeddedgo** [comment]
I'm very happy to see your work.

Some comments:

Using functions as config options is interesting approach but the `options ...func(*Device)` looks a little scary especially for non-Go programmers. AFAIK significant number of of people interested in Embedded Go aren't Go programmers.  Some name for `func(*Device)` type is need. Consider can you avoid dots too. Generally bare metal programmers like simple things that are easy to understand and debug. They very often complain any HAL for bloated code.

I think we can introduce your function based configuration concept as alternate method in spi package and as main method in spi/spiN packages. See for example [stm32/hal/spi](https://github.com/embeddedgo/stm32/tree/master/hal/spi). There is main spi package for more advanced users and ready to use spi1, spi2, spi3 sub-packages. The sub-packages provide reasonable defaults, easy to use interface and default configuration for many things needed like interrupts and DMA channels.

Name your driver `Driver` not `Device`. If you'll develop a DMA version name it `DriverDMA` or make the DMA version main driver and name no-DMA version `DriverNoDMA`.

Another thing is iotas. Use iotas only for constants where order doesn't matter. For configuration bits always use explicit numbers. You will come to the same conclusion very quickly as you will start debugging your drivers using GDB.

> Anyway, I will start on the PWM now and leave SPI for later as I think getting timers working would be useful and much more achievable.

Fill free to continue your work on SPI too. I didn't started any work on it yet.

> I'am also concerned about the struct visibility, currently only the HAL can access registers directly which would make it quite annoying if someone wanted to poke around, though perhaps it's better left hidden?

There will be p/spi package for playing with SPI registers directly. I'll try to generate it from SVD soon. In the HAL the registers should be hidden. A direct register access is allowed if providing a higher level interface doesn't make sense. See [kendryte/hal/gpio](https://github.com/embeddedgo/kendryte/blob/master/hal/gpio/port.go) or [kendryte/hal/gpiohs](https://github.com/embeddedgo/kendryte/blob/master/hal/gpiohs/port.go) `Port` as example.

As it seems to be not an issue but rather some kind of discussion I suggest to close it and move to [Embedded Go group](https://groups.google.com/g/embeddedgo). You can be a first person that start a topic on this group :) You can copy-paste your last question. I'll do the same with my answer. I think such discussion can be useful for other people. They rarely read github issues  especially closed ones.
